# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Monkey's Blog
email: monkey2maniu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Linux • Music • Open Source • Tech.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maniu.eu" # the base hostname & protocol for your site
twitter_username: monkey_maniu
github_username:  mmaniu

paginate: 10

gaaccount: ''

highlighter: rouge

gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE']
